# Generated by Django 5.1.2 on 2024-11-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='addet_to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
