# Generated by Django 5.1.2 on 2024-11-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
        ('reviews', '0002_reviews_addet_to'),
        ('store', '0006_rename_size_productsize_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
