# Generated by Django 5.1.2 on 2024-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_orders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to='shopping.cart'),
        ),
    ]
