# Generated by Django 5.1.2 on 2024-11-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_remove_orders_cart_orders_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('In progres', 'In progres'), ('Delivery', 'Delivery'), ('Completed', 'Completed')], default='In progres', max_length=11),
        ),
    ]
