# Generated by Django 5.1.2 on 2024-11-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_sum',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
