# Generated by Django 5.1.2 on 2024-11-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_orders_total_sum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
