# Generated by Django 5.1.2 on 2024-11-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug_name',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug_sex',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
