# Generated by Django 5.1.2 on 2024-11-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productsize_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addet_to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
