# Generated by Django 5.1.2 on 2024-11-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_addet_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='slug_sex',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sex',
            field=models.JSONField(default=list),
        ),
    ]
