# Generated by Django 5.1.2 on 2024-11-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productcategory_slug_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='size',
            new_name='name',
        ),
    ]
